### ISSUE TITLE
Add react-native support

### ISSUE THREAD

**Issue by retyui** [uploadcare/uploadcare-upload-client#289]
If you try to use this client to upload a file you will see the next error:

https://github.com/uploadcare/uploadcare-upload-client/blob/9abd0b059ce90e20e044d471625d55fa5e28527d/src/uploadFile/index.ts#L168

So, I have to use a hack to upload file

```js
import defaultSettings from '@uploadcare/upload-client/lib/defaultSettings';
import upload from '@uploadcare/upload-client/lib/uploadFile';

const populateOptionsWithSettings = (options) => ({
  ...defaultSettings,
  publicKey: 'XXXXX',
  ...options,
});

export const uploadFile = ({ size, name, type, uri }, options) =>
  upload({ name, size, type, uri }, populateOptionsWithSettings(options));
```

**Comment by nd0ut** [comment]
Hey @retyui
Thanks for report. 

With such input file format, we can't slice it into chunks to upload multipart. It's better to convert it to the Blob like this:

```javascript
const resp = await fetch(uri);
const blob = await resp.blob();
```
