### ISSUE TITLE
delete / delete-batch

### ISSUE THREAD

**Issue by sakulstra** [uploadcare/uploadcare-upload-client#338]
### I should be able to delete images via sdk¹

It's a little sad that i can only upload images via sdk, but have to use manual rest requests for everything else.
Would be good if i could at least delete & perhaps deleteBatch via sdk as it's supported, but just not implemented here: https://uploadcare.com/api-refs/rest-api/v0.5.0/#operation/deleteFileStorage.

My usecase would be uploading a users profile image - i want to delete the existing one and upload a new one.

---

In fact it would be good if things like, "list" would also be supported via sdk

**Comment by nd0ut** [comment]
Hey @sakulstra 
Unfortunately, this functionality isn't expected in the Upload Client. But you can use the unofficial [uploadcare-node](https://github.com/rexmorgan/uploadcare-node) package.
