### ISSUE TITLE
Add `save_in_group` option to document conversion method

### ISSUE THREAD

**Issue by nd0ut** [uploadcare/uploadcare-upload-client#495]
API refs: https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Conversion/operation/documentConvert

What we need:

Add `saveInGroup` options to the `convert` method. Note that the `convert` method currently accepts an option that specifies the conversion type (video or document), and the conversion options are the same for both. We should restrict the `saveInGroup` flag to be declared exclusively for document conversions.

**Comment by egordidenko** [comment]
@nd0ut done.
